kind: Service
apiVersion: v1
metadata:
  name: nflows-service
  namespace: aks-nflows-d
  #annotations:
    #service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: nflows-web-application
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080